### ISSUE TITLE
Request JetBranis Open Source Development License

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/tasks#13]
## 설명
```
Project description:
Develop a football website.
I have been running the website for several years and have stopped working, but I want to continue.
underlying technologies are Spring Framework, MongoDB, Elasticsearch, Virtual Machine, Kubernetes and Jenkins.
All code is open and we are looking for contributors. There are currently 2 contributors.
```

**Comment by Pyohwan** [comment]
## 답변
Hello Pyohwan,

We're writing to you in regards to your OSS development license request.

We've run an automated check of your GitHub repository to see if your open source project meets the [requirements of our Open Source Support Program](https://www.jetbrains.com/community/opensource/#support). Unfortunately, we found that at least one of these criteria was not met:

1. The project should be in active development. We need to see regular code commits submitted for the past 3 months or more. Readme.md and other non-code commits do not count. If you continue working on your project for a few more months, you're welcome to re-apply for support.

3. The requester should be a core project committer. A requester has to consistently contribute to the project for the past few months or be in the top-3 contributors for the past year. If you're not on the top contributor's list but still regularly maintain the project, please send us a link to your commits, and we will reconsider your request.

3. The project should be licensed under the MIT, Apache-2.0, or another comparable open source license. We haven't been able to locate such a license automatically in your repository. In case we missed it, please send us a link to the license file – we will check it manually.

If you believe that your application has been evaluated incorrectly, please email us back at opensource@jetbrains.com. We’ll be glad to look into your case and see how we can help you.

Thank you!

The Community Support team
JetBrains
https://www.jetbrains.com/
The Drive to Develop

**Comment by Pyohwan** [comment]
Dear Pyohwan,
Congratulations, your request to JetBrains for Open Source development license(s) has been approved! The license certificate is attached to this message.

Main facts about your license(s):

They are valid for one year. You will receive an automatic email reminder shortly before the license expiration date.
They should be used for developing your non-commercial open source projects only.
If you’ve received more than one license, please share them only with active contributors to your project.
To redeem your license(s), please click the link below:
[Take me to my license(s)](https://account.jetbrains.com/order/assets/4x4kozqpokxm9eshpte8cgab0)

If you find that JetBrains software has been useful for your project, please consider mentioning JetBrains support on your project’s homepage. Feel free to use the [JetBrains logo](https://www.jetbrains.com/company/brand/#logos-and-icons) and a link to our website such as https://jb.gg/OpenSourceSupport.

If you have any questions, please get in touch with us at opensource@jetbrains.com. We’ll be glad to help.

Kind regards,

JetBrains Community Support Team
https://www.jetbrains.com/
The Drive to Develop

**Comment by Pyohwan** [comment]
Hello Pyohwan,

Thanks for reaching out to us. I've checked your project again manually and I can see that it meets our requirements. The reason the check failed was because of the link that you provided (a general https://github.com/JakduK while our automated check can only read separate repositories).

I've renewed 2 free subscriptions for your open source project's further development.

Good luck with your work on it!

Kind regards,

Maria Mikheyshina
Community Support Team
JetBrains
http://www.jetbrains.com/
The Drive to Develop

**Comment by Pyohwan** [comment]
@silverprize 
라이선스 받을 이메일 알려주세요.

**Comment by Pyohwan** [comment]
@silverprize 
gmail 계정 있길래 그쪽으로 보내놨어요. 잘 쓰세요.

**Comment by silverprize** [comment]
> @silverprize gmail 계정 있길래 그쪽으로 보내놨어요. 잘 쓰세요.

@Pyohwan 따봉 눌렀는데 알림 가나요?

**Comment by Pyohwan** [comment]
@silverprize 
이모티콘은 원래 알림 발생 안합니다.
